-- Catálogo de posições identificáveis por página, seção e legenda.\nINSERT INTO public.site_media_slot_catalog(slot_key,label,section_name,page_name) VALUES
('home.hero.01','Foto principal 1 (abertura)','Abertura / Hero','home'),
('home.hero.02','Foto principal 2','Abertura / Hero','home'),
('home.hero.03','Foto principal 3','Abertura / Hero','home'),
('home.welcome.01','Foto à esquerda','Boas-vindas','home'),
('home.welcome.02','Foto à direita','Boas-vindas','home'),
('home.welcome.03','Foto pequena sobreposta','Boas-vindas','home'),
('home.services.01','Card Buffet completo','Nossos serviços','home'),
('home.services.02','Card Serviço de cozinha','Nossos serviços','home'),
('home.food-carousel.01','Fotografia 1','Carrossel 3D de pratos','home'),
('home.food-carousel.02','Fotografia 2','Carrossel 3D de pratos','home'),
('home.food-carousel.03','Fotografia 3','Carrossel 3D de pratos','home'),
('home.food-carousel.04','Fotografia 4','Carrossel 3D de pratos','home'),
('home.food-carousel.05','Fotografia 5','Carrossel 3D de pratos','home'),
('home.food-carousel.06','Fotografia 6','Carrossel 3D de pratos','home'),
('home.food-carousel.07','Fotografia 7','Carrossel 3D de pratos','home'),
('home.story-stack.01','Fotografia 1','Pilha de fotografias / História','home'),
('home.story-stack.02','Fotografia 2','Pilha de fotografias / História','home'),
('home.story-stack.03','Fotografia 3','Pilha de fotografias / História','home'),
('home.event-carousel.01','Fotografia 1','Carrossel curvo de eventos','home'),
('home.event-carousel.02','Fotografia 2','Carrossel curvo de eventos','home'),
('home.event-carousel.03','Fotografia 3','Carrossel curvo de eventos','home'),
('home.event-carousel.04','Fotografia 4','Carrossel curvo de eventos','home'),
('home.event-carousel.05','Fotografia 5','Carrossel curvo de eventos','home'),
('home.event-carousel.06','Fotografia 6','Carrossel curvo de eventos','home'),
('home.serving.01','Buffet à vontade','Jeitos de servir','home'),
('home.serving.02','Serviço à francesa','Jeitos de servir','home'),
('home.serving.03','Finger food','Jeitos de servir','home'),
('home.serving.04','Coquetel','Jeitos de servir','home'),
('home.mosaic.01','Fotografia 1','Mosaico animado','home'),
('home.mosaic.02','Fotografia 2','Mosaico animado','home'),
('home.mosaic.03','Fotografia 3','Mosaico animado','home'),
('home.mosaic.04','Fotografia 4','Mosaico animado','home'),
('home.mosaic.05','Fotografia 5','Mosaico animado','home'),
('home.mosaic.06','Fotografia 6','Mosaico animado','home'),
('home.mosaic.07','Fotografia 7','Mosaico animado','home'),
('home.final.01','Imagem de fundo da chamada final','Convite final','home'),
('services.hero.01','Imagem da abertura','Serviços / Hero','services'),
('services.cards.01','Buffet completo','Cards dos serviços','services'),
('services.cards.02','Serviço de cozinha','Cards dos serviços','services'),
('buffet.hero.01','Imagem da abertura','Buffet completo / Hero','buffet'),
('buffet.gallery.01','Fotografia 1','Buffet completo / Galeria','buffet'),
('buffet.gallery.02','Fotografia 2','Buffet completo / Galeria','buffet'),
('buffet.gallery.03','Fotografia 3','Buffet completo / Galeria','buffet'),
('buffet.gallery.04','Fotografia 4','Buffet completo / Galeria','buffet'),
('buffet.gallery.05','Fotografia 5','Buffet completo / Galeria','buffet'),
('buffet.gallery.06','Fotografia 6','Buffet completo / Galeria','buffet'),
('buffet.gallery.07','Fotografia 7','Buffet completo / Galeria','buffet'),
('buffet.gallery.08','Fotografia 8','Buffet completo / Galeria','buffet'),
('kitchen.hero.01','Imagem da abertura','Serviço de cozinha / Hero','kitchen'),
('kitchen.gallery.01','Fotografia 1','Serviço de cozinha / Galeria','kitchen'),
('kitchen.gallery.02','Fotografia 2','Serviço de cozinha / Galeria','kitchen'),
('kitchen.gallery.03','Fotografia 3','Serviço de cozinha / Galeria','kitchen'),
('kitchen.gallery.04','Fotografia 4','Serviço de cozinha / Galeria','kitchen'),
('kitchen.gallery.05','Fotografia 5','Serviço de cozinha / Galeria','kitchen'),
('kitchen.gallery.06','Fotografia 6','Serviço de cozinha / Galeria','kitchen'),
('kitchen.gallery.07','Fotografia 7','Serviço de cozinha / Galeria','kitchen'),
('kitchen.gallery.08','Fotografia 8','Serviço de cozinha / Galeria','kitchen'),
('story.hero.01','Imagem da abertura','Nossa história / Hero','story'),
('story.profile.01','Foto da Marli','Nossa história / Marli','story'),
('gallery.hero.01','Imagem da abertura','Galeria / Hero','gallery')
ON CONFLICT(slot_key) DO UPDATE SET label=EXCLUDED.label,section_name=EXCLUDED.section_name,page_name=EXCLUDED.page_name;
